project:
  type: website

website:
  title: "Metaphors of Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/meshik
      - icon: twitter
        href: https://x.com/DekelWainer
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



